name: Advanced Usage

on:
  push:
    branches: [katatumuri-maimai-patch-1]
  pull_request:
    branches: [katatumuri-maimai-patch-1]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown
          pip install requests
          
      - name: markdown2wp
        env:
          WP_USERNAME: ${{ secrets.WP_USERNAME }}
          WP_PASSWORD: ${{ secrets.WP_PASSWORD }}
        run: |
          file = $(git diff origin/${GITHUB_BASE_REF}..origin/${GITHUB_HEAD_REF} --name-only --diff-filter=A -- '*.md')
          test -e $file
          python markdown2wp.py "https://katatumuri.xyz/" "$WP_USERNAME" "$WP_PASSWORD" $file
          fi
