name: Advanced Usage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown
          pip install requests
      
      - name: markdown2wp
        env:
          WP_USERNAME: ${{ secrets.WP_USERNAME }}
          WP_PASSWORD: ${{ secrets.WP_PASSWORD }}
        run: |
          BEFORE_SHA=$(jq -r '.before' $GITHUB_EVENT_PATH)
          AFTER_SHA=$(jq -r '.after' $GITHUB_EVENT_PATH)
          git diff-tree --no-commit-id --name-only -r <commit-ish>
